version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: myplatefit-db
    restart: always
    environment:
      POSTGRES_DB: nutrition_db
      POSTGRES_USER: nutrition_user
      POSTGRES_PASSWORD: nutrition_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  myplatefit:
    build: .
    container_name: myplatefit-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/nutrition_db
      SPRING_DATASOURCE_USERNAME: nutrition_user
      SPRING_DATASOURCE_PASSWORD: nutrition_pass

      USDA_API_KEY: UvKA15LAdbmAjUz2itwEIk1yOHzjZAvywxcPM9SX
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USERNAME: bhandarirahul112@gmail.com
      MAIL_PASSWORD: bvozwoxyjapvvpik

    depends_on:
      - postgres

volumes:
  postgres_data:
