name: MyPlateFit CI/CD - GitHub Packages Version

on:
  push:
    branches: [ main ]

jobs:
  build-docker:
    runs-on: ubuntu-latest

    env:
      DOCKER_BUILDKIT: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build without tests
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -t myplatefit-app .

      - name: Log in to GitHub Packages Docker Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Tag Docker image for GitHub Packages
        run: docker tag myplatefit-app ghcr.io/${{ github.repository_owner }}/myplatefit-app:latest

      - name: Push Docker image to GitHub Packages
        run: docker push ghcr.io/${{ github.repository_owner }}/myplatefit-app:latest
