name: MyPlateFit CI/CD - DockerHub Version

on:
  push:
    branches: [ main ]

jobs:
  build-docker:
    runs-on: ubuntu-latest

    env:
      DOCKER_BUILDKIT: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build without tests
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -t myplatefit-app .

      - name: DockerHub Login
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Tag Docker image
        run: docker tag myplatefit-app ${{ secrets.DOCKERHUB_USERNAME }}/myplatefit-app:latest

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/myplatefit-app:latest
